### ISSUE TITLE
Choco Internalizer Fails Due To Environment Variable In Url

### ISSUE THREAD

**Issue by svenborer** [andrewmostello/prometheus-windows-exporter.install#15]
We would like to internalize the package but the internalizer script fails due to environment variable used for the version.

This could be fixed with the version variable being the actual version.

Thanks in advance!

**Comment by andrewmostello** [comment]
Sounds good. I'll replace `$env:chocolateyPackageVersion` with the actual version. It looks like Chocolatey recommends this now as well: https://docs.chocolatey.org/en-us/choco/features/version-number-normalization
