### ISSUE TITLE
Error with the 0.20.0 package published on Chocolatey

### ISSUE THREAD

**Issue by jantari** [andrewmostello/prometheus-windows-exporter.install#9]
Version 0.20.0 of this package as published on Chocolatey has an error in the chocolateyInstall.ps1 file:

https://community.chocolatey.org/packages/prometheus-windows-exporter.install/0.20.0#files

The following can be seen in the file as it is hosted currently in the Chocolatey repository:

```powershell
if ($pp["ExtraFlags"] -ne $null -and $pp["ExtraFlags"] -ne '') {
  $silentArgs += " --% EXTRA_FLAGS=`"$($pp["ExtraFlags"])`""
  Write-Host "Extra flags: `"$($pp["ExtraFlags"])`""
}
```

The `--%` should not be there.

It was not there in Version 0.19.0: https://community.chocolatey.org/packages/prometheus-windows-exporter.install/0.19.0#files  
and it is not there in this GitHub repo: https://github.com/andrewmostello/prometheus-windows-exporter.install/blob/master/tools/chocolateyinstall.ps1#L37-L40

Currently, the 0.20.0 chocolatey package install hangs indefinitely due to these invalid argument symbols when one uses the `ExtraFlags` parameter of the package.

**Comment by jantari** [comment]
This is the process commandline that the chocolatey 0.20.0 package runs for me:

```
"C:\Windows\System32\msiexec.exe" /i "C:\Users\administrator\AppData\Local\Temp\chocolatey\prometheus-windows-exporter.install\0.20.0\windows_exporter-0.20.0-amd64.msi" /quiet /norestart /l*v "C:\Users\administrator\AppData\Local\Temp\chocolatey\prometheus-windows-exporter.install.0.20.0.MsiInstall.log" --% EXTRA_FLAGS="--config.file="C:\ProgramData\windows_exporter\config.yml""
```

This hangs forever like I said, due to the invalid MSI argument  `--% EXTRA_FLAGS=`

**Comment by andrewmostello** [comment]
I've backed this out as of v0.21.0, so you should be all set now.

**Comment by jantari** [comment]
Thanks, 0.21.0 worked indeed
